package seedu.address.model.resume;

import java.util.ArrayList;
import java.util.List;

import seedu.address.model.entry.ResumeEntry;

/**
 * Represents a Section of a Resume generated by the app, containing a title
 * as well as a list of ResumeEntries.
 */
public class ResumeSection {
    public final String title;
    private final List<ResumeEntry> entryList;

    public ResumeSection(String title, List<ResumeEntry> entries) {
        this.title = title;
        entryList = new ArrayList<>(entries);
    }

    public List<ResumeEntry> getEntryList() {
        return this.entryList;
    }

    @Override
    public boolean equals(Object obj) {
        // short circuit if same object
        if (obj == this) {
            return true;
        }

        // instanceof handles nulls
        if (!(obj instanceof ResumeSection)) {
            return false;
        }

        // state check
        ResumeSection other = (ResumeSection) obj;
        return entryList.equals(other.getEntryList())
                && title.equals(other.title);
    }
}
