= Jiang Hengyuan- Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: ResuMaker

---

== Overview

ResuMaker is a fast, flexible and customizable resume generator aimed at computer science professionals. On top of the Command Line Interface where most of the user interaction take place, it also provides users with an intuitive and user friendly Graphic User Interface.

== Summary of contributions

* *Major enhancement*: Responsive Display of Expanded Entry
** What it does: It allows for the responsive display of the bullet description of an entry whenever a user edits the description of that particular entry.
** Justification: This is a useful feature as it provides a timely feedback to the user about the latest description of an entry that has been modified. Without this responsive feaure, the user may mistakenly feed in the wrong description to an entry without knowing it or he would have to manually select the edited entry to disclose its description.
** Credits: Let me acknowledge the se-edu/addressbook-level4 team in which their overall architecture design lays the foundation for the implementation of this enhancement and also for their idea on event driven design which is central to making the expanded entry display responsive.

* *Code contributed*:  [https://github.com[Functional code]] [https://github.com[Test code]] _{give links to collated code files}_

* *Other contributions*:
** Morphing AddressBook 4 to ResuMaker
*** Set up of Model Component Class Structure for ResumeEntry
** Enhancements to existing features: (to be updated)
** Test Handling
*** Addition of utility class such as EntryBuilder to facilitate unit testing of Model related classes
** Documentation:
*** Modified Command Format section under the feature section of the User Guide
** Community:
*** PRs reviewed (with non-trivial review comments)


== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=hengyuanUG]


== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=entryManagement]


