= Marvin Tan Xu Dong - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: ResuMaker

---

== Overview

ResuMaker is a fast and flexible resume generator, optimised for students in the School of Computing. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 10 kLoC.

ResuMaker simplifies the process of writing resumes.
Instead of having to rewrite your resume every time you want to apply for a new job, ResuMaker allows users to easily maintain a record of entries describing their past experiences such as work, education, or side projects,
each of which can have tags applied. Whenever one needs to apply for a new job, they simply have to specify a template file, which states which tags should be included.
The application can then generate a resume in Markdown format displaying all the relevant entries, without any manual organizing on the user's part.

== Summary of contributions

* *Major enhancement*: added *the ability to use templates to specify resume formats*
** What it does: This allows the user to use template text files to specify how the resume will be generated, in terms of the ordering and title of sections, and which entries will appear under each section based on its tags.
** Justification: This feature enables one of the core value propositions of our product, which is to be able to easily generate resumes for different contexts.
While the application will hold all of the user's experiences as entries,
templates allow the user to customize the generated resume for specific purposes, or depending on which company they are applying to, by specifying the types of entries to include.
** Highlights: Templates accommodate a basic boolean logic system. In the template text files, users can specify the tags to include in a sum-of-products form.
The user can specify a list of tag groups, where an entry which fulfils at least one would be included. Each tag group is a tag or the logical AND of any number of them.
E.g. `java python&datascience swift` means "entries should be tagged with (java) OR (python AND datascience) OR (swift)".


* *Minor enhancement*: added the ability for users to specify their particulars and contact details in the preferences file,
for them to be displayed in the generated resume.

* *Minor enhancement*: implemented the saving of entries into an XML file.

* *Code contributed*:
https://nus-cs2103-ay1819s1.github.io/cs2103-dashboard/#=undefined&search=marvintxd[Project Code Dashboard]

* *Other contributions*:

** Project management:
*** Managed releases `v1.3` - `v1.5rc` (3 releases) on GitHub
** Enhancements to existing features:
*** Updated the GUI color scheme (Pull requests https://github.com[#33], https://github.com[#34])
*** Wrote additional tests for existing features to increase coverage from 88% to 92% (Pull requests https://github.com[#36], https://github.com[#38])
** Documentation:
*** Did cosmetic tweaks to existing contents of the User Guide: https://github.com[#14]
*** Updated component diagrams: [ ]
** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com/CS2103-AY1819S1-W17-1/main/pull/267[#267], https://github.com/CS2103-AY1819S1-W17-1/main/pull/150[#150]
*** Bugs reported on teammates' features: https://github.com/CS2103-AY1819S1-W17-1/main/issues/290[#290]
*** Contributed to forum discussions (examples:  https://github.com[1], https://github.com[2], https://github.com[3], https://github.com[4])
*** Reported bugs and suggestions for other teams in the class (examples:  https://github.com[1], https://github.com[2], https://github.com[3])
*** Some parts of the history feature I added was adopted by several other class mates (https://github.com[1], https://github.com[2])
** Tools:
*** Set up Travis CI and autopublishing of docs for the project

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=template]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=template]
