= Gu Wangfan - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: ResuMaker

---

== Overview

ResuMaker is a fast and flexible resume generator optimised for
students of the School of Computing at the National University of Singapore (NUS SOC),
and can help customise one's resumes for specific jobs or requirements.

ResuMaker allows a user to store entries of information relevant to their career.
These entries can be about work experience, personal skills, education history or anything else they would want in a resume.
To facilitate easy browsing and management, entries each belong to a category and can have tags added to them. +
When a resume is needed for, for instance, a job application, the user prepares a template file
which dictates the sections they want in the resume and lists the tags which decide which entries should be shown.
The user can then generate a resume file which will display entries previously stored in the ResuMaker
that match the criteria specified in the template. This resume file is created in markdown,
a commonly used file format that can then easily be converted to other formats like Word or PDF documents by a variety of other tools.

_[DIAGRAM SHOWING WORKFLOW]_

== Summary of contributions

* *Major enhancement*: Added *the ability to generate a resume and save it to a file*.
**	This feature uses the specifications of a given template to filter and organise the entries stored in ResuMaker
into a visually appealing resume file, saved in the markdown format for easy conversion to other commonly used document formats.
**	This enhancement makes use of various components across ResuMaker and was also designed to be modular enough
to allow for easy extension. For instance, the use of markdown to format the text of the resume was designed
such that it would be easy to change the layout of the resume (such as changing the font size of its section headers
or adding other content to the resume) or even switch to a different file format altogether.
**	An link:https://github.com/Steppschuh/Java-Markdown-Generator[external library] was used to handle the
generation of markdown text in a more organised way rather than manipulating the text directly.
While this functionality was important, it is not essential to the feature - generating the markdown text of the resume
could have been done without it, although it would have either taken more work to develop the functionality separately
or been much messier.

* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] _{give links to collated code files}_

* *Other contributions*:
** Project management:
*** Designed a link:https://github.com/CS2103-AY1819S1-W17-1/main/issues/62[neat, organised format] for managing development issues for use by the project team.
*** Coordinated API design between team members across components and features to ensure smooth integration.
*** Reviewed test coverage and quality.
** Documentation:
*** Fixed writing style issues in the
link:https://github.com/CS2103-AY1819S1-W17-1/main/commit/f59e486c11887eb49c214738fb989161d591ba49[User Guide] and
link:https://github.com/CS2103-AY1819S1-W17-1/main/commit/e3509a0af98fce9277896e5d03338ff1c20f72e1[Developer Guide].
** Community:
*** Reviewed pull requests (with non-trivial review comments):
link:https://github.com/CS2103-AY1819S1-W17-1/main/pull/119[#119],
link:https://github.com/CS2103-AY1819S1-W17-1/main/pull/152[#152],
link:https://github.com/CS2103-AY1819S1-W17-1/main/pull/163[#163]
** Tools:
*** Integrated a third party library to the project to generate markdown text:
link:https://github.com/CS2103-AY1819S1-W17-1/main/pull/33[#33], link:https://github.com/CS2103-AY1819S1-W17-1/main/pull/112[#112].

== Contributions to the User Guide


|===
|_Here are some sections I contributed to the User Guide which showcase my ability to write documentation for end-users._
|===

include::../UserGuide.adoc[tag=resume]

== Contributions to the Developer Guide

|===
|_Here are some sections I contributed to the Developer Guide which showcase the technical depth of my contributions to the project, as well as my ability to document them._
|===

include::../DeveloperGuide.adoc[tag=resume]
